apiVersion: batch/v1
kind: Job
metadata:
  name: library-importer
  namespace: mekstrike
spec:
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "library-importer"
        dapr.io/log-as-json: "true"
    spec:
      containers:
      - name: mekstrike-importer
        image: mekstrike-importer
        imagePullPolicy: Never
      restartPolicy: Never