apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: mekstrike-instrumentation
  namespace: mekstrike
spec:
  exporter:
    endpoint: http://zipkin-apm-collector-collector.monitoring.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1"