// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: armybuilder/src/main/proto/armybuilder.proto

package abprotos

import (
	unit "github.com/corstijank/mekstrike/domain/unit"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArmyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lights        int32                  `protobuf:"varint,1,opt,name=lights,proto3" json:"lights,omitempty"`
	Mediums       int32                  `protobuf:"varint,2,opt,name=mediums,proto3" json:"mediums,omitempty"`
	Heavies       int32                  `protobuf:"varint,3,opt,name=heavies,proto3" json:"heavies,omitempty"`
	Assaults      int32                  `protobuf:"varint,4,opt,name=assaults,proto3" json:"assaults,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArmyRequest) Reset() {
	*x = ArmyRequest{}
	mi := &file_armybuilder_src_main_proto_armybuilder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArmyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArmyRequest) ProtoMessage() {}

func (x *ArmyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_armybuilder_src_main_proto_armybuilder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArmyRequest.ProtoReflect.Descriptor instead.
func (*ArmyRequest) Descriptor() ([]byte, []int) {
	return file_armybuilder_src_main_proto_armybuilder_proto_rawDescGZIP(), []int{0}
}

func (x *ArmyRequest) GetLights() int32 {
	if x != nil {
		return x.Lights
	}
	return 0
}

func (x *ArmyRequest) GetMediums() int32 {
	if x != nil {
		return x.Mediums
	}
	return 0
}

func (x *ArmyRequest) GetHeavies() int32 {
	if x != nil {
		return x.Heavies
	}
	return 0
}

func (x *ArmyRequest) GetAssaults() int32 {
	if x != nil {
		return x.Assaults
	}
	return 0
}

type ArmyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Units         []*unit.Stats          `protobuf:"bytes,1,rep,name=units,proto3" json:"units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArmyResponse) Reset() {
	*x = ArmyResponse{}
	mi := &file_armybuilder_src_main_proto_armybuilder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArmyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArmyResponse) ProtoMessage() {}

func (x *ArmyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_armybuilder_src_main_proto_armybuilder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArmyResponse.ProtoReflect.Descriptor instead.
func (*ArmyResponse) Descriptor() ([]byte, []int) {
	return file_armybuilder_src_main_proto_armybuilder_proto_rawDescGZIP(), []int{1}
}

func (x *ArmyResponse) GetUnits() []*unit.Stats {
	if x != nil {
		return x.Units
	}
	return nil
}

var File_armybuilder_src_main_proto_armybuilder_proto protoreflect.FileDescriptor

const file_armybuilder_src_main_proto_armybuilder_proto_rawDesc = "" +
	"\n" +
	",armybuilder/src/main/proto/armybuilder.proto\x12\x19net.mekstrike.armybuilder\x1a\x16domain/unit/unit.proto\"u\n" +
	"\vArmyRequest\x12\x16\n" +
	"\x06lights\x18\x01 \x01(\x05R\x06lights\x12\x18\n" +
	"\amediums\x18\x02 \x01(\x05R\amediums\x12\x18\n" +
	"\aheavies\x18\x03 \x01(\x05R\aheavies\x12\x1a\n" +
	"\bassaults\x18\x04 \x01(\x05R\bassaults\"F\n" +
	"\fArmyResponse\x126\n" +
	"\x05units\x18\x01 \x03(\v2 .net.mekstrike.domain.unit.StatsR\x05unitsB9\n" +
	"\x19net.mekstrike.armybuilderB\x11ArmyBuilderProtosZ\t/abprotosb\x06proto3"

var (
	file_armybuilder_src_main_proto_armybuilder_proto_rawDescOnce sync.Once
	file_armybuilder_src_main_proto_armybuilder_proto_rawDescData []byte
)

func file_armybuilder_src_main_proto_armybuilder_proto_rawDescGZIP() []byte {
	file_armybuilder_src_main_proto_armybuilder_proto_rawDescOnce.Do(func() {
		file_armybuilder_src_main_proto_armybuilder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_armybuilder_src_main_proto_armybuilder_proto_rawDesc), len(file_armybuilder_src_main_proto_armybuilder_proto_rawDesc)))
	})
	return file_armybuilder_src_main_proto_armybuilder_proto_rawDescData
}

var file_armybuilder_src_main_proto_armybuilder_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_armybuilder_src_main_proto_armybuilder_proto_goTypes = []any{
	(*ArmyRequest)(nil),  // 0: net.mekstrike.armybuilder.ArmyRequest
	(*ArmyResponse)(nil), // 1: net.mekstrike.armybuilder.ArmyResponse
	(*unit.Stats)(nil),   // 2: net.mekstrike.domain.unit.Stats
}
var file_armybuilder_src_main_proto_armybuilder_proto_depIdxs = []int32{
	2, // 0: net.mekstrike.armybuilder.ArmyResponse.units:type_name -> net.mekstrike.domain.unit.Stats
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_armybuilder_src_main_proto_armybuilder_proto_init() }
func file_armybuilder_src_main_proto_armybuilder_proto_init() {
	if File_armybuilder_src_main_proto_armybuilder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_armybuilder_src_main_proto_armybuilder_proto_rawDesc), len(file_armybuilder_src_main_proto_armybuilder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_armybuilder_src_main_proto_armybuilder_proto_goTypes,
		DependencyIndexes: file_armybuilder_src_main_proto_armybuilder_proto_depIdxs,
		MessageInfos:      file_armybuilder_src_main_proto_armybuilder_proto_msgTypes,
	}.Build()
	File_armybuilder_src_main_proto_armybuilder_proto = out.File
	file_armybuilder_src_main_proto_armybuilder_proto_goTypes = nil
	file_armybuilder_src_main_proto_armybuilder_proto_depIdxs = nil
}
