// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: armybuilder/src/main/proto/armybuilder.proto

package abprotos

import (
	unit "github.com/corstijank/mekstrike/src/common/go/unit"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArmyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lights   int32 `protobuf:"varint,1,opt,name=lights,proto3" json:"lights,omitempty"`
	Mediums  int32 `protobuf:"varint,2,opt,name=mediums,proto3" json:"mediums,omitempty"`
	Heavies  int32 `protobuf:"varint,3,opt,name=heavies,proto3" json:"heavies,omitempty"`
	Assaults int32 `protobuf:"varint,4,opt,name=assaults,proto3" json:"assaults,omitempty"`
}

func (x *ArmyRequest) Reset() {
	*x = ArmyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_armybuilder_src_main_proto_armybuilder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArmyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArmyRequest) ProtoMessage() {}

func (x *ArmyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_armybuilder_src_main_proto_armybuilder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArmyRequest.ProtoReflect.Descriptor instead.
func (*ArmyRequest) Descriptor() ([]byte, []int) {
	return file_armybuilder_src_main_proto_armybuilder_proto_rawDescGZIP(), []int{0}
}

func (x *ArmyRequest) GetLights() int32 {
	if x != nil {
		return x.Lights
	}
	return 0
}

func (x *ArmyRequest) GetMediums() int32 {
	if x != nil {
		return x.Mediums
	}
	return 0
}

func (x *ArmyRequest) GetHeavies() int32 {
	if x != nil {
		return x.Heavies
	}
	return 0
}

func (x *ArmyRequest) GetAssaults() int32 {
	if x != nil {
		return x.Assaults
	}
	return 0
}

type ArmyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Units []*unit.UnitStats `protobuf:"bytes,1,rep,name=units,proto3" json:"units,omitempty"`
}

func (x *ArmyResponse) Reset() {
	*x = ArmyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_armybuilder_src_main_proto_armybuilder_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArmyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArmyResponse) ProtoMessage() {}

func (x *ArmyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_armybuilder_src_main_proto_armybuilder_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArmyResponse.ProtoReflect.Descriptor instead.
func (*ArmyResponse) Descriptor() ([]byte, []int) {
	return file_armybuilder_src_main_proto_armybuilder_proto_rawDescGZIP(), []int{1}
}

func (x *ArmyResponse) GetUnits() []*unit.UnitStats {
	if x != nil {
		return x.Units
	}
	return nil
}

var File_armybuilder_src_main_proto_armybuilder_proto protoreflect.FileDescriptor

var file_armybuilder_src_main_proto_armybuilder_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x61, 0x72, 0x6d, 0x79, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x65, 0x72, 0x2f, 0x73, 0x72,
	0x63, 0x2f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x72, 0x6d,
	0x79, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19,
	0x6e, 0x65, 0x74, 0x2e, 0x6d, 0x65, 0x6b, 0x73, 0x74, 0x72, 0x69, 0x6b, 0x65, 0x2e, 0x61, 0x72,
	0x6d, 0x79, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x65, 0x72, 0x1a, 0x1a, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2f, 0x67, 0x6f, 0x2f, 0x75, 0x6e, 0x69, 0x74, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x75, 0x0a, 0x0b, 0x41, 0x72, 0x6d, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x64, 0x69, 0x75, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d,
	0x65, 0x64, 0x69, 0x75, 0x6d, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x76, 0x69, 0x65,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x68, 0x65, 0x61, 0x76, 0x69, 0x65, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x61, 0x73, 0x73, 0x61, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x61, 0x73, 0x73, 0x61, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x4a, 0x0a, 0x0c,
	0x41, 0x72, 0x6d, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x05,
	0x75, 0x6e, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6e, 0x65,
	0x74, 0x2e, 0x6d, 0x65, 0x6b, 0x73, 0x74, 0x72, 0x69, 0x6b, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x2e, 0x55, 0x6e, 0x69, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x52, 0x05, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x42, 0x39, 0x0a, 0x19, 0x6e, 0x65, 0x74, 0x2e,
	0x6d, 0x65, 0x6b, 0x73, 0x74, 0x72, 0x69, 0x6b, 0x65, 0x2e, 0x61, 0x72, 0x6d, 0x79, 0x62, 0x75,
	0x69, 0x6c, 0x64, 0x65, 0x72, 0x42, 0x11, 0x41, 0x72, 0x6d, 0x79, 0x42, 0x75, 0x69, 0x6c, 0x64,
	0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x5a, 0x09, 0x2f, 0x61, 0x62, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_armybuilder_src_main_proto_armybuilder_proto_rawDescOnce sync.Once
	file_armybuilder_src_main_proto_armybuilder_proto_rawDescData = file_armybuilder_src_main_proto_armybuilder_proto_rawDesc
)

func file_armybuilder_src_main_proto_armybuilder_proto_rawDescGZIP() []byte {
	file_armybuilder_src_main_proto_armybuilder_proto_rawDescOnce.Do(func() {
		file_armybuilder_src_main_proto_armybuilder_proto_rawDescData = protoimpl.X.CompressGZIP(file_armybuilder_src_main_proto_armybuilder_proto_rawDescData)
	})
	return file_armybuilder_src_main_proto_armybuilder_proto_rawDescData
}

var file_armybuilder_src_main_proto_armybuilder_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_armybuilder_src_main_proto_armybuilder_proto_goTypes = []interface{}{
	(*ArmyRequest)(nil),    // 0: net.mekstrike.armybuilder.ArmyRequest
	(*ArmyResponse)(nil),   // 1: net.mekstrike.armybuilder.ArmyResponse
	(*unit.UnitStats)(nil), // 2: net.mekstrike.common.unit.UnitStats
}
var file_armybuilder_src_main_proto_armybuilder_proto_depIdxs = []int32{
	2, // 0: net.mekstrike.armybuilder.ArmyResponse.units:type_name -> net.mekstrike.common.unit.UnitStats
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_armybuilder_src_main_proto_armybuilder_proto_init() }
func file_armybuilder_src_main_proto_armybuilder_proto_init() {
	if File_armybuilder_src_main_proto_armybuilder_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_armybuilder_src_main_proto_armybuilder_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArmyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_armybuilder_src_main_proto_armybuilder_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArmyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_armybuilder_src_main_proto_armybuilder_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_armybuilder_src_main_proto_armybuilder_proto_goTypes,
		DependencyIndexes: file_armybuilder_src_main_proto_armybuilder_proto_depIdxs,
		MessageInfos:      file_armybuilder_src_main_proto_armybuilder_proto_msgTypes,
	}.Build()
	File_armybuilder_src_main_proto_armybuilder_proto = out.File
	file_armybuilder_src_main_proto_armybuilder_proto_rawDesc = nil
	file_armybuilder_src_main_proto_armybuilder_proto_goTypes = nil
	file_armybuilder_src_main_proto_armybuilder_proto_depIdxs = nil
}
