apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
  namespace: mekstrike
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin-apm-collector-collector.monitoring.svc.cluster.local:9411/api/v2/spans"
