// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: domain/unit/unit.proto

package unit

import (
	battlefield "github.com/corstijank/mekstrike/domain/battlefield"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Stats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Pointvalue    int32                  `protobuf:"varint,3,opt,name=pointvalue,proto3" json:"pointvalue,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Size          int32                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Movement      string                 `protobuf:"bytes,6,opt,name=movement,proto3" json:"movement,omitempty"`
	Role          string                 `protobuf:"bytes,7,opt,name=role,proto3" json:"role,omitempty"`
	Shortdmg      int32                  `protobuf:"varint,8,opt,name=shortdmg,proto3" json:"shortdmg,omitempty"`
	Meddmg        int32                  `protobuf:"varint,9,opt,name=meddmg,proto3" json:"meddmg,omitempty"`
	Longdmg       int32                  `protobuf:"varint,10,opt,name=longdmg,proto3" json:"longdmg,omitempty"`
	Ovhdmg        int32                  `protobuf:"varint,11,opt,name=ovhdmg,proto3" json:"ovhdmg,omitempty"`
	Armor         int32                  `protobuf:"varint,12,opt,name=armor,proto3" json:"armor,omitempty"`
	Struct        int32                  `protobuf:"varint,13,opt,name=struct,proto3" json:"struct,omitempty"`
	Specials      []string               `protobuf:"bytes,14,rep,name=specials,proto3" json:"specials,omitempty"`
	Image         string                 `protobuf:"bytes,15,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_domain_unit_unit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_domain_unit_unit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_domain_unit_unit_proto_rawDescGZIP(), []int{0}
}

func (x *Stats) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stats) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Stats) GetPointvalue() int32 {
	if x != nil {
		return x.Pointvalue
	}
	return 0
}

func (x *Stats) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Stats) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Stats) GetMovement() string {
	if x != nil {
		return x.Movement
	}
	return ""
}

func (x *Stats) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Stats) GetShortdmg() int32 {
	if x != nil {
		return x.Shortdmg
	}
	return 0
}

func (x *Stats) GetMeddmg() int32 {
	if x != nil {
		return x.Meddmg
	}
	return 0
}

func (x *Stats) GetLongdmg() int32 {
	if x != nil {
		return x.Longdmg
	}
	return 0
}

func (x *Stats) GetOvhdmg() int32 {
	if x != nil {
		return x.Ovhdmg
	}
	return 0
}

func (x *Stats) GetArmor() int32 {
	if x != nil {
		return x.Armor
	}
	return 0
}

func (x *Stats) GetStruct() int32 {
	if x != nil {
		return x.Struct
	}
	return 0
}

func (x *Stats) GetSpecials() []string {
	if x != nil {
		return x.Specials
	}
	return nil
}

func (x *Stats) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type Location struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	BattlefieldId string                   `protobuf:"bytes,1,opt,name=battlefieldId,proto3" json:"battlefieldId,omitempty"`
	Position      *battlefield.Coordinates `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Heading       int32                    `protobuf:"varint,3,opt,name=heading,proto3" json:"heading,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_domain_unit_unit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_domain_unit_unit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_domain_unit_unit_proto_rawDescGZIP(), []int{1}
}

func (x *Location) GetBattlefieldId() string {
	if x != nil {
		return x.BattlefieldId
	}
	return ""
}

func (x *Location) GetPosition() *battlefield.Coordinates {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Location) GetHeading() int32 {
	if x != nil {
		return x.Heading
	}
	return 0
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *Stats                 `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	Location      *Location              `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Active        bool                   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_domain_unit_unit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_domain_unit_unit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_domain_unit_unit_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetStats() *Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *Data) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Data) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Data) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type DeployRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BattlefieldId string                 `protobuf:"bytes,1,opt,name=battlefieldId,proto3" json:"battlefieldId,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Stats         *Stats                 `protobuf:"bytes,3,opt,name=stats,proto3" json:"stats,omitempty"`
	Corner        string                 `protobuf:"bytes,4,opt,name=corner,proto3" json:"corner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployRequest) Reset() {
	*x = DeployRequest{}
	mi := &file_domain_unit_unit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest) ProtoMessage() {}

func (x *DeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_unit_unit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest.ProtoReflect.Descriptor instead.
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return file_domain_unit_unit_proto_rawDescGZIP(), []int{3}
}

func (x *DeployRequest) GetBattlefieldId() string {
	if x != nil {
		return x.BattlefieldId
	}
	return ""
}

func (x *DeployRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *DeployRequest) GetStats() *Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *DeployRequest) GetCorner() string {
	if x != nil {
		return x.Corner
	}
	return ""
}

var File_domain_unit_unit_proto protoreflect.FileDescriptor

const file_domain_unit_unit_proto_rawDesc = "" +
	"\n" +
	"\x16domain/unit/unit.proto\x12\x19net.mekstrike.domain.unit\x1a$domain/battlefield/battlefield.proto\"\xef\x02\n" +
	"\x05Stats\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1e\n" +
	"\n" +
	"pointvalue\x18\x03 \x01(\x05R\n" +
	"pointvalue\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x05R\x04size\x12\x1a\n" +
	"\bmovement\x18\x06 \x01(\tR\bmovement\x12\x12\n" +
	"\x04role\x18\a \x01(\tR\x04role\x12\x1a\n" +
	"\bshortdmg\x18\b \x01(\x05R\bshortdmg\x12\x16\n" +
	"\x06meddmg\x18\t \x01(\x05R\x06meddmg\x12\x18\n" +
	"\alongdmg\x18\n" +
	" \x01(\x05R\alongdmg\x12\x16\n" +
	"\x06ovhdmg\x18\v \x01(\x05R\x06ovhdmg\x12\x14\n" +
	"\x05armor\x18\f \x01(\x05R\x05armor\x12\x16\n" +
	"\x06struct\x18\r \x01(\x05R\x06struct\x12\x1a\n" +
	"\bspecials\x18\x0e \x03(\tR\bspecials\x12\x14\n" +
	"\x05image\x18\x0f \x01(\tR\x05image\"\x95\x01\n" +
	"\bLocation\x12$\n" +
	"\rbattlefieldId\x18\x01 \x01(\tR\rbattlefieldId\x12I\n" +
	"\bposition\x18\x02 \x01(\v2-.net.mekstrike.domain.battlefield.CoordinatesR\bposition\x12\x18\n" +
	"\aheading\x18\x03 \x01(\x05R\aheading\"\xad\x01\n" +
	"\x04Data\x126\n" +
	"\x05stats\x18\x01 \x01(\v2 .net.mekstrike.domain.unit.StatsR\x05stats\x12?\n" +
	"\blocation\x18\x02 \x01(\v2#.net.mekstrike.domain.unit.LocationR\blocation\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06active\"\x9b\x01\n" +
	"\rDeployRequest\x12$\n" +
	"\rbattlefieldId\x18\x01 \x01(\tR\rbattlefieldId\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x126\n" +
	"\x05stats\x18\x03 \x01(\v2 .net.mekstrike.domain.unit.StatsR\x05stats\x12\x16\n" +
	"\x06corner\x18\x04 \x01(\tR\x06cornerBN\n" +
	"\x19net.mekstrike.domain.unitB\x04UnitZ+github.com/corstijank/mekstrike/domain/unitb\x06proto3"

var (
	file_domain_unit_unit_proto_rawDescOnce sync.Once
	file_domain_unit_unit_proto_rawDescData []byte
)

func file_domain_unit_unit_proto_rawDescGZIP() []byte {
	file_domain_unit_unit_proto_rawDescOnce.Do(func() {
		file_domain_unit_unit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_unit_unit_proto_rawDesc), len(file_domain_unit_unit_proto_rawDesc)))
	})
	return file_domain_unit_unit_proto_rawDescData
}

var file_domain_unit_unit_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_domain_unit_unit_proto_goTypes = []any{
	(*Stats)(nil),                   // 0: net.mekstrike.domain.unit.Stats
	(*Location)(nil),                // 1: net.mekstrike.domain.unit.Location
	(*Data)(nil),                    // 2: net.mekstrike.domain.unit.Data
	(*DeployRequest)(nil),           // 3: net.mekstrike.domain.unit.DeployRequest
	(*battlefield.Coordinates)(nil), // 4: net.mekstrike.domain.battlefield.Coordinates
}
var file_domain_unit_unit_proto_depIdxs = []int32{
	4, // 0: net.mekstrike.domain.unit.Location.position:type_name -> net.mekstrike.domain.battlefield.Coordinates
	0, // 1: net.mekstrike.domain.unit.Data.stats:type_name -> net.mekstrike.domain.unit.Stats
	1, // 2: net.mekstrike.domain.unit.Data.location:type_name -> net.mekstrike.domain.unit.Location
	0, // 3: net.mekstrike.domain.unit.DeployRequest.stats:type_name -> net.mekstrike.domain.unit.Stats
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_domain_unit_unit_proto_init() }
func file_domain_unit_unit_proto_init() {
	if File_domain_unit_unit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_unit_unit_proto_rawDesc), len(file_domain_unit_unit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_unit_unit_proto_goTypes,
		DependencyIndexes: file_domain_unit_unit_proto_depIdxs,
		MessageInfos:      file_domain_unit_unit_proto_msgTypes,
	}.Build()
	File_domain_unit_unit_proto = out.File
	file_domain_unit_unit_proto_goTypes = nil
	file_domain_unit_unit_proto_depIdxs = nil
}
