// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: domain/battlefield/battlefield.proto

package battlefield

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Coordinates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinates) Reset() {
	*x = Coordinates{}
	mi := &file_domain_battlefield_battlefield_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinates) ProtoMessage() {}

func (x *Coordinates) ProtoReflect() protoreflect.Message {
	mi := &file_domain_battlefield_battlefield_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinates.ProtoReflect.Descriptor instead.
func (*Coordinates) Descriptor() ([]byte, []int) {
	return file_domain_battlefield_battlefield_proto_rawDescGZIP(), []int{0}
}

func (x *Coordinates) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Coordinates) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Cell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coordinates   *Coordinates           `protobuf:"bytes,1,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cell) Reset() {
	*x = Cell{}
	mi := &file_domain_battlefield_battlefield_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cell) ProtoMessage() {}

func (x *Cell) ProtoReflect() protoreflect.Message {
	mi := &file_domain_battlefield_battlefield_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cell.ProtoReflect.Descriptor instead.
func (*Cell) Descriptor() ([]byte, []int) {
	return file_domain_battlefield_battlefield_proto_rawDescGZIP(), []int{1}
}

func (x *Cell) GetCoordinates() *Coordinates {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *Cell) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_domain_battlefield_battlefield_proto protoreflect.FileDescriptor

const file_domain_battlefield_battlefield_proto_rawDesc = "" +
	"\n" +
	"$domain/battlefield/battlefield.proto\x12 net.mekstrike.domain.battlefield\")\n" +
	"\vCoordinates\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"k\n" +
	"\x04Cell\x12O\n" +
	"\vcoordinates\x18\x01 \x01(\v2-.net.mekstrike.domain.battlefield.CoordinatesR\vcoordinates\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04typeBc\n" +
	" net.mekstrike.domain.battlefieldB\vBattlefieldZ2github.com/corstijank/mekstrike/domain/battlefieldb\x06proto3"

var (
	file_domain_battlefield_battlefield_proto_rawDescOnce sync.Once
	file_domain_battlefield_battlefield_proto_rawDescData []byte
)

func file_domain_battlefield_battlefield_proto_rawDescGZIP() []byte {
	file_domain_battlefield_battlefield_proto_rawDescOnce.Do(func() {
		file_domain_battlefield_battlefield_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_battlefield_battlefield_proto_rawDesc), len(file_domain_battlefield_battlefield_proto_rawDesc)))
	})
	return file_domain_battlefield_battlefield_proto_rawDescData
}

var file_domain_battlefield_battlefield_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_domain_battlefield_battlefield_proto_goTypes = []any{
	(*Coordinates)(nil), // 0: net.mekstrike.domain.battlefield.Coordinates
	(*Cell)(nil),        // 1: net.mekstrike.domain.battlefield.Cell
}
var file_domain_battlefield_battlefield_proto_depIdxs = []int32{
	0, // 0: net.mekstrike.domain.battlefield.Cell.coordinates:type_name -> net.mekstrike.domain.battlefield.Coordinates
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_domain_battlefield_battlefield_proto_init() }
func file_domain_battlefield_battlefield_proto_init() {
	if File_domain_battlefield_battlefield_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_battlefield_battlefield_proto_rawDesc), len(file_domain_battlefield_battlefield_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_battlefield_battlefield_proto_goTypes,
		DependencyIndexes: file_domain_battlefield_battlefield_proto_depIdxs,
		MessageInfos:      file_domain_battlefield_battlefield_proto_msgTypes,
	}.Build()
	File_domain_battlefield_battlefield_proto = out.File
	file_domain_battlefield_battlefield_proto_goTypes = nil
	file_domain_battlefield_battlefield_proto_depIdxs = nil
}
