apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: monitoring
spec:
  version: 8.11.4
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false