apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: monitoring
spec:
  version: 8.11.4
  count: 1
  elasticsearchRef:
    name: elasticsearch
  config:
    server:
      basePath: "/kibana"
      rewriteBasePath: true
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    service:
      spec:
        sessionAffinity: ClientIP
  podTemplate:
    spec:
      containers:
        - name: kibana
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: "/kibana/login"
              port: 5601

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-ingress
  namespace: monitoring
spec:
  rules:
    - host: "localhost"
      http:
        paths:
          - pathType: Prefix
            path: "/kibana"
            backend:
              service:
                name: kibana-kb-http
                port:
                  number: 5601