apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: zipkin-apm-collector
  namespace: monitoring
spec:
  managementState: managed 
  config:
    receivers:
      zipkin:
        endpoint: 0.0.0.0:9411
    exporters:
      otlp/jaeger:
        endpoint: jaeger-collector:4317
        tls:
          insecure: true  
    service:
      pipelines:
        traces:
          receivers: [zipkin]
          exporters: [otlp/jaeger] 
